# CRUD entity mappings
#   fk: array of foreign access_key field -> entity mappings
#   searchable: array of fields that can be searched

parameters:
    hyperion.entities:
        account:
            fk: { }
            searchable:
                - id
                - name

        project:
            fk: { account_id: account, credential_id: credential }
            searchable:
                - id
                - account
                - name
                - bake_status
                - baked_image_id
                - source_image_id
                - packager
                - update_system_packages

        environment:
            fk: { project_id: project, credential_id: credential }
            searchable:
                - id
                - project
                - name
                - environment_type
                - tenancy
                - instance_size
                - network

        credential:
            fk: { account_id: account }
            searchable:
                - id
                - account
                - provider
                - access_key
                - region

        action:
            fk: { project_id: project }
            searchable:
                - id
                - project
                - name
                - state

        proxy:
            fk: { account_id: account }
            searchable:
                - id
                - account
                - type
                - hostname
                - port
                - username
                - password

        repository:
            fk: { account_id: account, proxy_id: proxy }
            searchable:
                - id
                - account
                - proxy
                - type
                - url
                - username
                - password
                - private_key
                - tag

        distribution:
            fk: { environment_id: environment }
            searchable:
                - id
                - environment
                - name
                - status

        instance:
            fk: { distribution_id: distribution }
            searchable:
                - id
                - distribution
                - instance_id
                - name
                - state
