services:
    hyperion.kernel.listener.request:
        class: Hyperion\ApiBundle\Listeners\HyperionKernelListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
