services:
    hyperion.kernel.listener.request:
        class: Hyperion\ApiBundle\Listener\HyperionKernelListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    hyperion.entity_validator:
        class: Hyperion\ApiBundle\Service\EntityValidator
        arguments: [ '%hyperion.entities%' ]
