Hyperion\ApiBundle\Entity\Project:
    properties:
        account:
            - NotNull: ~
        name:
            - NotBlank: ~
            - Length:
                min: 2
                max: 50
