imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          false
    use_controller: false
    bundles:        [ ]
    filters:
        cssrewrite: ~
        sass:
            bin: %sass_path%
            apply_to: "\.scss$"
        uglifycss:
            bin: %uglifycss_path%
            apply_to: "\.scss$"
        uglifyjs2:
            bin: %uglifyjs_path%
            apply_to: "\.js$"
    assets:
        main_css:
            inputs:
                - %kernel.root_dir%/Resources/public/css/*
                - @HyperionApiBundle/Resources/public/css/*
                - %kernel.root_dir%/../vendor/twbs/bootstrap-sass/assets/stylesheets/bootstrap.scss
            output: assets/styles.css
        main_js:
            inputs:
                - %kernel.root_dir%/Resources/public/js/*
                - @HyperionApiBundle/Resources/public/js/*
                - %kernel.root_dir%/../vendor/twbs/bootstrap-sass/assets/javascripts/bootstrap/*
                - %kernel.root_dir%/../vendor/twbs/bootstrap-sass/assets/javascripts/bootstrap.js
            output: assets/scripts.js


# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# REST API
fos_rest:
    view:
        formats:
            rss: false
            xml: true
            json: true
            yml: true
        templating_formats:
            html: false
    routing_loader:
        default_format: json

# Braincrafted Configuration
braincrafted_bootstrap:
    less_filter: none
    assets_dir: "%kernel.root_dir%/../vendor/twbs/bootstrap-sass/assets"
    output_dir: "assets"
    auto_configure:
        assetic: false
        twig: true
