# API Server v1
hyperion_api:
    resource: @HyperionApiBundle/Resources/config/routing_api.yml
    prefix:   /api/v1

# Admin Interface
hyperion_admin:
    resource: @HyperionApiBundle/Resources/config/routing_admin.yml
    prefix:   /admin

# Dashboard
hyperion_dashboard:
    resource: @HyperionApiBundle/Resources/config/routing_dashboard.yml
    prefix:   /dashboard

# Optional - contains a welcome home page
hyperion_static:
    resource: Hyperion\ApiBundle\Controller\StaticController
    type:     annotation

