# API v1
hyperion_api_stack:
    resource: Hyperion\ApiBundle\Controller\StackController
    type:     rest
    prefix:   /api/v1/

hyperion_api_crud:
    resource: Hyperion\ApiBundle\Controller\CrudController
    type:     rest
    prefix:   /api/v1/entity/

# Admin
hyperion_admin:
    resource: @HyperionApiBundle/Resources/config/routing_admin.yml
    prefix:   /admin

# Dashboard
hyperion_dashboard:
    resource: @HyperionApiBundle/Resources/config/routing_dashboard.yml
    prefix:   /dashboard

# Optional - contains a welcome home page
hyperion_api_static:
    resource: Hyperion\ApiBundle\Controller\StaticController
    type:     annotation

