# API v1
hyperion_api_crud:
    resource: Hyperion\ApiBundle\Controller\CrudController
    type:     rest
    prefix:   /api/v1/

hyperion_api_stack:
    resource: Hyperion\ApiBundle\Controller\StackController
    type:     rest
    prefix:   /api/v1/

# Optional - contains a welcome home page
hyperion_api_static:
    resource: Hyperion\ApiBundle\Controller\StaticController
    type:     annotation

